/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YangiRouteImport } from './routes/yangi'
import { Route as XatchoplarRouteImport } from './routes/xatchoplar'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as IndexRouteImport } from './routes/index'

const YangiRoute = YangiRouteImport.update({
  id: '/yangi',
  path: '/yangi',
  getParentRoute: () => rootRouteImport,
} as any)
const XatchoplarRoute = XatchoplarRouteImport.update({
  id: '/xatchoplar',
  path: '/xatchoplar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/profil': typeof ProfilRoute
  '/xatchoplar': typeof XatchoplarRoute
  '/yangi': typeof YangiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/profil': typeof ProfilRoute
  '/xatchoplar': typeof XatchoplarRoute
  '/yangi': typeof YangiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/profil': typeof ProfilRoute
  '/xatchoplar': typeof XatchoplarRoute
  '/yangi': typeof YangiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/katalog' | '/profil' | '/xatchoplar' | '/yangi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/katalog' | '/profil' | '/xatchoplar' | '/yangi'
  id: '__root__' | '/' | '/katalog' | '/profil' | '/xatchoplar' | '/yangi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KatalogRoute: typeof KatalogRoute
  ProfilRoute: typeof ProfilRoute
  XatchoplarRoute: typeof XatchoplarRoute
  YangiRoute: typeof YangiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yangi': {
      id: '/yangi'
      path: '/yangi'
      fullPath: '/yangi'
      preLoaderRoute: typeof YangiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xatchoplar': {
      id: '/xatchoplar'
      path: '/xatchoplar'
      fullPath: '/xatchoplar'
      preLoaderRoute: typeof XatchoplarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KatalogRoute: KatalogRoute,
  ProfilRoute: ProfilRoute,
  XatchoplarRoute: XatchoplarRoute,
  YangiRoute: YangiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
